name: pip_services3_swagger
version: 1.0.1
description: Portable abstractions and patterns for Pip.Services in Dart
homepage: https://github.com/pip-services3-dart/pip-services3-swagger-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pip_services3_commons: ^1.1.3
  pip_services3_components: ^1.1.2
  pip_services3_rpc: ^1.2.3

  shelf_router: ^1.1.2
  shelf: ^1.2.0

dev_dependencies:
  test: ^1.17.12